apiVersion: v1
kind: Secret
metadata:
  name: project-secrets
type: Opaque
data:
  username: cm9vdAo=          #root
  root_password: YWRtaW4K       #admin
  service_host: bXlzcWwtc2VydmljZQo=    #mysql-serivce
  db_name: c29oZWxzaGFpa2gK   #sohelshaikh
