apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: admin
        # valueFrom:
        #   secretKeyRef:
        #     name: flaskapi-secrets
        #     key: db_root_password
