# apiVersion: v1
# kind: Pod
# metadata:
#   name: mysqlnew
#   labels:
#     app: mysqlnew
# spec:
#   containers:
#   - name: mysql
#     image: mysql:8.0
#     ports:
#       - containerPort: 3306
#     env:
#       - name: MYSQL_ROOT_PASSWORD
#         #value: admin
#         valueFrom:
#           secretKeyRef:
#             name: project-secrets
#             key: root_password
#     volumeMounts:
#       - name: project-pv
#         mountPath: /var/lib/mysql
#   volumes:
#     - name: project-pv
#       persistentVolumeClaim:
#         claimName: project-pvc

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
  labels:
    app:  mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name:  mysql
        image:  mysql:5.7
        # resources:
        #   limits:
        #     memory: "256M"
        #     cpu: "900m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: db_root_password
        volumeMounts:
          - name: project-pv
            mountPath: /var/lib/mysql
            subPath: mysql
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: project-pv
        persistentVolumeClaim:
          claimName: project-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config