apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
  namespace: default
  labels:
    app: project-pvc
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi